Update 23.11
allen11137/explore-with-me pull request #1
Opened 2023-11-23 16:25 UTC by allen11137

2023-11-23 19:31 UTC, z8q requested changes

2023-11-23 19:31 UTC, z8q commented on docker-compose.yml
> +      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
Еще будут нужны
```
- SPRING_DATASOURCE_USERNAME=root
- SPRING_DATASOURCE_PASSWORD=root
```
Для stats-server тоже

2023-11-23 19:31 UTC, z8q commented on docker-compose.yml
> +      - stats-server
ewm-service и stats-server независимы, без 31-й строки должно работать

2023-11-23 19:31 UTC, z8q commented on stats/stats-server/pom.xml
> +    <dependencyManagement>
Вот этот блок `<dependencyManagement>` надо вынести в родительский пом, чтобы здесь можно было использовать в таком виде:
```
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
            </dependency>
```

2023-11-23 19:31 UTC, z8q commented on stats/stats-server/pom.xml
> +    <dependencyManagement>
Те зависимости, которые уже включены в spring boot’овский BOM spring-boot-dependencies, от которого наследуется spring-boot-starter-parent, должны быть без версий.
Это выполняется)
А если используем что-то, чего там нет — тогда такая зависимость должна быть прописана в блоке `<dependencyManagement>` корневого pom’а, где и будет указана версия. А в pom’е самого модуля (где зависимость непосредственно используется) должно быть всё равно без версии. Этим обеспечивается центральное место для управления версиями зависимостей и соответственно порядок в проекте.

2023-11-23 19:41 UTC, allen11137 commented on docker-compose.yml
> +      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
Добавила

2023-11-23 19:42 UTC, allen11137 commented on docker-compose.yml
> +      - stats-server
Исправила

2023-11-23 20:14 UTC, allen11137 commented on stats/stats-server/pom.xml
> +    <dependencyManagement>
Готово

2023-11-24 18:34 UTC, z8q requested changes

2023-11-24 18:34 UTC, z8q commented on stats/stats-server/pom.xml
>      </dependencyManagement>
Тут все таки пришлось оставить dependencyManagement?

2023-11-26 16:18 UTC, allen11137 commented on stats/stats-server/pom.xml
>      </dependencyManagement>
Поправила)

2023-11-26 16:18 UTC, merged